services:
  backend:
    tmpfs:
      - /tmp
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "${BACKEND_PORT}:3000"
  frontend:
    tmpfs:
      - /tmp
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    environment:
      VITE_API_URL: /api
      VITE_BACKEND_URL: http://backend:3000
    ports:
      - "5173:5173"

volumes:
  backend_node_modules:
  frontend_node_modules: